version: '3.8'

services:
  notification:
    image: werikoliveira/notificator:latest
    container_name: notification-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - DATABASE_DIR=/app/data
      - API_SECRET_KEY=sua_chave_aqui
    labels:
      - "com.casaos.description=Central de Notificações e Alertas"
      - "com.casaos.icon=https://cdn-icons-png.flaticon.com/512/3238/3238468.png"
      - "com.casaos.category=Utilities"
      - "com.casaos.port=3000"