version: '3.8'

services:
  dashboard:
    image: werikoliveira/notificator:0.1
    container_name: am-dashboard
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - DATABASE_DIR=/app/data
      # Chave de API (opcional, para compatibilidade)
      - API_SECRET_KEY=
      # Credenciais do Admin
      - ADMIN_USERNAME=WerikS
      - ADMIN_PASSWORD=We12wi25k#3912*
      # Configurações para integração com Meta Ads (Dashboard)
      - META_ADS_ACCESS_TOKEN=sua_chave_aqui
      - META_ADS_ACCOUNT_ID=sua_conta_aqui
      # Configurações para IA (Chat)
      - AI_API_URL=https://opencode.ai/zen/go/v1/chat/completions
      - AI_API_KEY=sua_api_key_aqui
      - AI_MODEL=mimo-v2.5
    labels:
      - "com.casaos.description=AM Dashboard Traffic - Dashboard Meta Ads"
      - "com.casaos.icon=https://cdn-icons-png.flaticon.com/512/3238/3238468.png"
      - "com.casaos.category=Utilities"
      - "com.casaos.port=3000"